apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deepfield

resources:
  - namespace.yaml
  - secrets-template.yaml
  - configmap.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - backend-deployment.yaml
  - services.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: deepfield
  app.kubernetes.io/part-of: deepfield
