"""DeepField run report generators."""

import json
from dataclasses import asdict
from typing import Optional

from app.metrics.funnel import SignalFunnel
from app.metrics.capacity import CapacityEstimate


def generate_run_report_json(
    run_id: str,
    mode: str,
    profile: str,
    funnel: SignalFunnel,
    capacity: Optional[CapacityEstimate] = None,
    duration_ms: float = 0,
) -> str:
    report = {
        "run_id": run_id,
        "mode": mode,
        "profile": profile,
        "duration_ms": round(duration_ms, 2),
        "signal_funnel": asdict(funnel),
    }
    if capacity:
        report["capacity_projection"] = asdict(capacity)
    return json.dumps(report, indent=2, default=str)


def generate_run_report_md(
    run_id: str,
    mode: str,
    profile: str,
    funnel: SignalFunnel,
    capacity: Optional[CapacityEstimate] = None,
    duration_ms: float = 0,
) -> str:
    lines = [
        "# DeepField Run Report",
        "",
        "## Run Summary",
        f"- **Run ID:** {run_id}",
        f"- **Mode:** {mode}",
        f"- **Profile:** {profile}",
        f"- **Duration:** {duration_ms:.0f}ms",
        "",
        "## Signal Funnel",
        f"- Raw signals: {funnel.raw_signals_received:,}",
        f"- Normalized: {funnel.normalized_signals:,}",
        f"- Dropped: {funnel.dropped_signals:,}",
        f"- Deduped: {funnel.deduped_signals:,}",
        f"- Suppressed transients: {funnel.suppressed_transients:,}",
        f"- Retained: {funnel.retained_signals:,}",
        f"- Correlated findings: {funnel.correlated_findings:,}",
        f"- Reasoning tasks: {funnel.reasoning_tasks_created:,}",
        f"- Final insights: {funnel.final_insights_created:,}",
        "",
        "## Compression",
        f"- Signal reduction: {funnel.signal_reduction_percent:.1f}%",
        f"- LLM escalation rate: {funnel.llm_escalation_rate_percent:.4f}%",
        f"- **Reasoning Compression Ratio: {funnel.reasoning_compression_ratio:,.1f}:1**",
    ]
    if capacity:
        lines.extend([
            "",
            "## Capacity Projection",
            f"- Max reasoning tasks/min: {capacity.max_reasoning_tasks_per_minute:.1f}",
            f"- Max raw signals/min: {capacity.max_raw_signals_per_minute:,.0f}",
            f"- **Projected clusters supported: {capacity.projected_clusters_supported}**",
            f"- p95 latency: {capacity.p95_latency_ms:.0f}ms",
        ])
    lines.extend(["", "---", f"*Generated by DeepField — {mode} mode*", ""])
    return "\n".join(lines)
